### ISSUE TITLE
sg update breaks module 

### ISSUE THREAD

**Issue by andrewmitchell-21** [cyberlabrs/terraform-aws-opensearch#19]
https://github.com/cyberlabrs/terraform-aws-opensearch/commit/95533900ab281592548dde7e6a55ca7837b584ae var should match input sg_ids not sg_id, I am unable to create a PR to fix

**Comment by MatanHeledPort** [comment]
My bad!
Opening a PR soon

**Comment by MatanHeledPort** [comment]
https://github.com/cyberlabrs/terraform-aws-opensearch/pull/21
Please approve (:
