### ISSUE TITLE
Make Service Role Creation Optional

### ISSUE THREAD

**Issue by redSlug** [cyberlabrs/terraform-aws-opensearch#5]
We need service role creation to be optional because our use case requires we OpenSearch clusters in the same AWS account

https://github.com/cyberlabrs/terraform-aws-opensearch/blob/b319c420c7c395da82d794d8c1ae7cda8c0c5686/main.tf#L52

**Comment by andros3** [comment]
Greetings, I will try to solve it as soon as possible.
